repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: detect-private-key
  - id: no-commit-to-branch
    args:
    - "-b master"
  rev: v2.5.0
- repo: https://github.com/psf/black
  hooks:
  - id: black
    language_version: python3.8
  rev: 19.10b0
- repo: https://github.com/pre-commit/mirrors-isort
  hooks:
  - id: isort
  rev: v4.3.21
- repo: https://gitlab.com/pycqa/flake8
  hooks:
  - id: flake8
  rev: 3.8.1